//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/MyInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MyInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MyInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MyInputs"",
    ""maps"": [
        {
            ""name"": ""ModelView"",
            ""id"": ""9775c39e-aee8-49ea-9c13-2000fd4034cb"",
            ""actions"": [
                {
                    ""name"": ""PrimaryTouchPosition"",
                    ""type"": ""Value"",
                    ""id"": ""01009f7c-aab8-46c0-b9e0-7c042dcbe212"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Touch0"",
                    ""type"": ""Value"",
                    ""id"": ""dba1dd46-fb4f-4b30-96bf-fb4294e1a0fc"",
                    ""expectedControlType"": ""Touch"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Touch1"",
                    ""type"": ""Value"",
                    ""id"": ""22d26d88-7279-403e-89a0-07dfdf31908e"",
                    ""expectedControlType"": ""Touch"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SwipeAxis"",
                    ""type"": ""Value"",
                    ""id"": ""b43a4b12-d137-489f-9c1b-89669f17ab2e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PrimaryTouchButton"",
                    ""type"": ""Button"",
                    ""id"": ""7b40ea6b-a7d2-44c7-9281-be20d9f38a66"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5af80613-e34c-4ade-b689-cf71d8fe13af"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryTouchPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab03da03-a72a-4f01-87d1-180e1d311334"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryTouchPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed445683-da85-44c1-8def-9c54d5f400fc"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwipeAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""62213467-204e-4ecc-a07a-2460574e320b"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwipeAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""ee12b30d-b4ab-40bd-935a-8e50f390f1f6"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwipeAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""012cbeb0-5c14-43d7-b26b-732a09d80f04"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwipeAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2d9fc95d-ee06-4b16-80b5-cb128b7d981a"",
                    ""path"": ""<Touchscreen>/touch0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9d769c5-b1b9-461e-af1f-3b2840f5ceda"",
                    ""path"": ""<Touchscreen>/touch1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5fb0716d-f391-4390-bd15-b65b750bf9b9"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryTouchButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3e09cf5a-d1da-44b3-832d-6e7685c7b6b1"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryTouchButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ModelView
        m_ModelView = asset.FindActionMap("ModelView", throwIfNotFound: true);
        m_ModelView_PrimaryTouchPosition = m_ModelView.FindAction("PrimaryTouchPosition", throwIfNotFound: true);
        m_ModelView_Touch0 = m_ModelView.FindAction("Touch0", throwIfNotFound: true);
        m_ModelView_Touch1 = m_ModelView.FindAction("Touch1", throwIfNotFound: true);
        m_ModelView_SwipeAxis = m_ModelView.FindAction("SwipeAxis", throwIfNotFound: true);
        m_ModelView_PrimaryTouchButton = m_ModelView.FindAction("PrimaryTouchButton", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ModelView
    private readonly InputActionMap m_ModelView;
    private List<IModelViewActions> m_ModelViewActionsCallbackInterfaces = new List<IModelViewActions>();
    private readonly InputAction m_ModelView_PrimaryTouchPosition;
    private readonly InputAction m_ModelView_Touch0;
    private readonly InputAction m_ModelView_Touch1;
    private readonly InputAction m_ModelView_SwipeAxis;
    private readonly InputAction m_ModelView_PrimaryTouchButton;
    public struct ModelViewActions
    {
        private @MyInputs m_Wrapper;
        public ModelViewActions(@MyInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @PrimaryTouchPosition => m_Wrapper.m_ModelView_PrimaryTouchPosition;
        public InputAction @Touch0 => m_Wrapper.m_ModelView_Touch0;
        public InputAction @Touch1 => m_Wrapper.m_ModelView_Touch1;
        public InputAction @SwipeAxis => m_Wrapper.m_ModelView_SwipeAxis;
        public InputAction @PrimaryTouchButton => m_Wrapper.m_ModelView_PrimaryTouchButton;
        public InputActionMap Get() { return m_Wrapper.m_ModelView; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ModelViewActions set) { return set.Get(); }
        public void AddCallbacks(IModelViewActions instance)
        {
            if (instance == null || m_Wrapper.m_ModelViewActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ModelViewActionsCallbackInterfaces.Add(instance);
            @PrimaryTouchPosition.started += instance.OnPrimaryTouchPosition;
            @PrimaryTouchPosition.performed += instance.OnPrimaryTouchPosition;
            @PrimaryTouchPosition.canceled += instance.OnPrimaryTouchPosition;
            @Touch0.started += instance.OnTouch0;
            @Touch0.performed += instance.OnTouch0;
            @Touch0.canceled += instance.OnTouch0;
            @Touch1.started += instance.OnTouch1;
            @Touch1.performed += instance.OnTouch1;
            @Touch1.canceled += instance.OnTouch1;
            @SwipeAxis.started += instance.OnSwipeAxis;
            @SwipeAxis.performed += instance.OnSwipeAxis;
            @SwipeAxis.canceled += instance.OnSwipeAxis;
            @PrimaryTouchButton.started += instance.OnPrimaryTouchButton;
            @PrimaryTouchButton.performed += instance.OnPrimaryTouchButton;
            @PrimaryTouchButton.canceled += instance.OnPrimaryTouchButton;
        }

        private void UnregisterCallbacks(IModelViewActions instance)
        {
            @PrimaryTouchPosition.started -= instance.OnPrimaryTouchPosition;
            @PrimaryTouchPosition.performed -= instance.OnPrimaryTouchPosition;
            @PrimaryTouchPosition.canceled -= instance.OnPrimaryTouchPosition;
            @Touch0.started -= instance.OnTouch0;
            @Touch0.performed -= instance.OnTouch0;
            @Touch0.canceled -= instance.OnTouch0;
            @Touch1.started -= instance.OnTouch1;
            @Touch1.performed -= instance.OnTouch1;
            @Touch1.canceled -= instance.OnTouch1;
            @SwipeAxis.started -= instance.OnSwipeAxis;
            @SwipeAxis.performed -= instance.OnSwipeAxis;
            @SwipeAxis.canceled -= instance.OnSwipeAxis;
            @PrimaryTouchButton.started -= instance.OnPrimaryTouchButton;
            @PrimaryTouchButton.performed -= instance.OnPrimaryTouchButton;
            @PrimaryTouchButton.canceled -= instance.OnPrimaryTouchButton;
        }

        public void RemoveCallbacks(IModelViewActions instance)
        {
            if (m_Wrapper.m_ModelViewActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IModelViewActions instance)
        {
            foreach (var item in m_Wrapper.m_ModelViewActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ModelViewActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ModelViewActions @ModelView => new ModelViewActions(this);
    public interface IModelViewActions
    {
        void OnPrimaryTouchPosition(InputAction.CallbackContext context);
        void OnTouch0(InputAction.CallbackContext context);
        void OnTouch1(InputAction.CallbackContext context);
        void OnSwipeAxis(InputAction.CallbackContext context);
        void OnPrimaryTouchButton(InputAction.CallbackContext context);
    }
}
